srsran/srsRAN_4G

- srslte/examples/CMakeLists.txt
without, linkage fails if UHD shared library is not installed in the
default location on Fedora 22.
> examples: Added UHD library dir to CMakeLists.txt

- srslte/examples/pdsch_enodeb.c
In pdsch_enode, when requesting "nf" frames be written to file, only 1 full frame was written. The "nf++" index increment line was inside the subframe for loop. This edit pulls it outside the for loop so that "nf" full frames are written to file.
> pdsch_enode: write requested number of frames to file

- srslte/lib/rf/rf_uhd_imp.c
We free `devices_str` inside `rf_uhd_open` since it's in local scope.
> free UHD handles upon RF closure

- srslte/examples/synch_file.c
- srslte/lib/ch_estimation/test/refsignal_ul_test.c
- srslte/lib/mimo/test/precoding_test.c
- srslte/lib/modem/test/modem_test.c
- srslte/lib/phch/sch.c
- srslte/lib/phch/test/prach_test.c
- srslte/lib/phch/test/pucch_test.c
- srslte/lib/scrambling/test/scrambling_test.c
Should solve some PW.PRINTF_ARG_MISMATCH issues
> coverity: timeval.tv_usec is 'long int', not 'int'

- srslte/examples/synch_file.c
- srslte/lib/modem/test/modem_test.c
I introduced these coverity issues in my last PR ; sorry about that
> Do not demote timeval members to int ; fix elapsed time unit in modem test

- srslte/lib/phch/prach.c
This PRACH opportunity routine was mis-considering the option 14 of the PRACH Configuration Index table present in 3GPP specifications 36.211, 5.7.1-2. Basically the setup of `prach_sf_config` private table of `prach.c` file is correct in all the other options (`index%16`), but in the case of 14 it's wrong.
As for the other options, when selecting this entry in the table (the 15th), you assume that the `nof_sf` of the `srslte_prach_sf_config_t` structure is -1, and this will ultimately skip the sub-frames nested loop and returns always false. As result option 14 opportunity check always returned false, instead of always true (as 3GPP table indicates).
By inserting a quick check specialized for this option (PRACH Configuration Index 14) at the begin, you skip any additional and useless …
> Fixed bug in srslte_prach_tti_opportunity()

- lib/include/srslte/common/pcap.h
This patch includes SysFrameNumber (SFN) in PCAP files, as it is expected by the Wireshark mac-lte dissector. The tag name was changed accordingly. I've just adapted the Wireshark implementation. If there's some standard, I'm not aware of it.
It seems to work just as intended, but please double-check.
The type change was just to make things clear to me, maybe the rest of `MAC_Context_Info_t` should use the explicit types, too. But might be more a theoretical problem.
[packet-mac-lte.c#L2327](https://github.com/wireshark/wireshark/blob/2832f4e97d77324b4e46aac40dae0ce898ae559d/epan/dissectors/packet-mac-lte.c#L2327)
```c
case MAC_LTE_FRAME_SUBFRAME_TAG:
{
guint16 sfn_sf = tvb_get_ntohs(tvb, offset);
p_mac_lte_info->sysframeNumber = (sfn_sf >> 4) & 0x03ff;
p_mac_lte_info->subframeNumber = …
```
> Write SFN to MAC-LTE PCAP file

- srsenb/src/mac/mac.cc
This fix will write the RAR to the pcap file.
> fixed enb pcap mac

- srsenb/src/phy/phy.cc
storage for log service objects vs using index operator.
> use vector push_back method to allocate required

- srsue/src/upper/rrc.cc
UE random ID was limited to `2^40 = 42` instead of `2**40`.
Even with the bitmask corrected, values were limited to `2**31`, because `rand()` returns values up to `RAND_MAX = INT_MAX`, i.e. 31 Bits only.
Therefore bitwise generation is introduced. I'm not sure about `rand()` speeds, so maybe this introduces problems.
> Fix bug in random UE ID generation

- lib/include/srslte/common/interfaces_common.h
- srsue/hdr/ue_base.h
- srsue/src/main.cc
- srsue/src/ue.cc
- srsue/src/upper/nas.cc
- srsue/ue.conf.example
This allows users to force an APN in PDN connectivity request.
Actually I'm not sure if the following line is ok, since I do not hand a pointer to `nas::init`, but the `struct` itself:
```cpp
srslte_nas_config_t nas_cfg(1, args->apn); /* RB_ID_SRB1 */
nas.init(&usim, &rrc, &gw, &nas_log, nas_cfg); 
```
> Add APN to config and PDN connectivity request

- srsenb/src/upper/rrc.cc
Initialize the E_RABFailedToSetupListCtxtSURes_present and CriticalityDiagnostics_present members of the LIBLTE_S1AP_MESSAGE_INITIALCONTEXTSETUPRESPONSE_STRUCT to false to prevent "[S1AP] [E] Failed to send InitialContextSetupResponse" errors. When these members are set to false the liblte_s1ap_pack_initialcontextsetupresponse (lib/src/asn1/liblte_s1ap.cc) routine ignores the corresponding (uninitialized) structures when serializing the response pdu.
> LIBLTE_S1AP_MESSAGE_INITIALCONTEXTSETUPRESPONSE_STRUCT initialization fix

- srsenb/src/upper/rrc.cc
- srsepc/hdr/mme/s1ap_nas_transport.h
- srsepc/src/mme/s1ap_ctx_mngmt_proc.cc
- srsepc/src/mme/s1ap_nas_transport.cc
This branch solves problems wrong key eNodeB derivation, I encountered when the TMSI is not known. See more on the mailing list "RRC Security Mode Command Failure".
> NAS key enb derivation fix

- srsue/src/upper/nas.cc
- srsue/src/upper/pcsc_usim.cc
- srsue/src/upper/rrc.cc
Access to the keys allows easy analysis of PCAPs.
> add keys to loglevel 'info' to simplify PCAP analysis

- srsenb/src/phy/phch_worker.cc
Small type when SINR value is used for the RSSI cumulative moving average value instead of the actual RSSI value in the eNB uplink metrics for the PHCH worker.
> fix typo in metrics rssi CMA calculation

- lib/include/srslte/phy/utils/mat.h
- lib/include/srslte/phy/utils/simd.h
- lib/src/phy/rf/rf_soapy_imp.c
Fixes for the issues that I encountered while trying to compile and run srsLTE on RPI 3. 
Fix compilation issues with NEON enabled. Also, I noticed that it attempts to compile NEON code even when CMake option 'DISABLE_SIMD' is set (not sure if this is intentional) and I was not able to find a way  to disable NEON code using CMake options (without modifying CMakeList.txt).
Fix runtime timestamp overflow with soapy driver when 'time_t secs' is 32-bit (on 32bit system).
> Fixes for srsLTE on ARM

- lib/src/phy/rf/rf_blade_imp.c
The rf_calibration function for blade RF was assging dc_gain to
BLADERF_CORR_FPGA_PHASE and dc_phase to BLADERF_CORR_FPGA_GAIN. This hot
fix corrects the value assignments in both rf_blade_set_tx_cal and
rf_blade_set_rx_cal functions.
> ASSIGN CORRECT VALUES FROM BLADERF MANUAL CALIBRATION TO CORRECTION FUNCTION

- srsepc/src/hss/hss.cc
During the resync procedure, the security_milenage_f1_star generates a
MAC_S value that does not match the MAC_S value reported in AUTS. This
posts a security risk.
According to 3GPP TS 33.102 version 11.5.1 section 6.3.3, the AMF used
to calculate MAC-S assumes a dummy value of all zeros so that it does
not need to be transmitted in the clear in the re-synch message.
This patch corrects this problem. MAC_S reported by AUTS matches the
MAC_S calculated using f1_star function after the fix.
> Set AMF to all zeros during resync

- srsenb/hdr/upper/rrc.h
- srsenb/src/upper/rrc.cc
- srsue/src/upper/nas.cc
in rapid multiple ue attach condition enb to ue reconfig data could be clobbered before it is sent. Made temporary config storage unique per ue (rnti).
Above condition was causing an integrity check error at the receiver but was ignored resulting in multiple ue's with the same ip address.
> eNB erab_info clobber and UE integrity check result in duplicate ip address (#215 rebased)

- lib/src/upper/pdcp.cc
The block of code calls an erase on an iterator controlling the for loop, which invalidates the iterator. After the first iteration of the loop, the post-increment on the iterator inside the for statement is not guaranteed to work - on Fedora 29 it causes a segfault. Move the iterator increment operation to a post-increment inside the call to erase.
> Remove undefined increment of an erased iterator.

- srsenb/src/upper/s1ap.cc
When s1c_bind_addr is set to default and not correct it caused a segmentation fault (noticed with srsepc, and was fine with open air interface EPC) without showing any additional error.
Added an appropriate error message on bind function, the error handling was missing.
> add error handling on binding s1c socket

- lib/src/phy/enb/enb_dl.c
I noticed that with the extended cyclic prefix enabled, the PSS was missing. It turned out that the SSS had been put on top of the PSS because it was using the wrong cyclic prefix mode.
There is still something wrong with extended prefix mode as phy_dl_test can't pass traffic, but this is a small step towards that working.
> Fix enb putting the SSS in the wrong place with ext CP enabled.

- srsepc/src/hss/hss.cc
This is an easy bugfix to improve handling of csv files with blank lines.
> Fix bug wherein blank lines or trailing newlines causes parsing of user_db.csv to fail

- srsenb/enb.conf.example
- srsenb/hdr/enb.h
- srsenb/src/main.cc
- srsenb/src/stack/mac/mac.cc
* MAC pcap generation could be enabled in the config file, but never actually happened -> fix
* MAC pcap files don't include SIB -> update documentation
* WRITE_SIB_PCAP didn't build anymore -> fix
> various MAC pcap related fixes

- srsenb/hdr/enb.h
- srsenb/src/enb_cfg_parser.cc
- srsenb/src/enb_cfg_parser.h
This adds the required missing bits to the eNB config file parser
to enable minimalistic support of parsing SIB7 configuration.
SIB7 contains GERAN (GSM) neighbor cell information, which is important
if you are operating a combined 2G+4G netowrk and want to assist the UEs
to reselect GSM cells once they move out of LTE coverage.
An example SIB7 section looks as follows:
sib7 = {
t_resel_geran = 1;
carrier_freqs_info_list =
(
{
cell_resel_prio = 0;
ncc_permitted = 255;
q_rx_lev_min = 0;
thresh_x_high = 7;
thresh_x_low = 7;
start_arfcn = 871;
band_ind = "dcs1800";
explicit_list_of_arfcns = ( 873, 875, 877 );
}
);
};
Closes: #357
> SRSENB: Add SIB7 (GERAN neighbor) support

- lib/src/phy/io/filesource.c
Hi all,
I have noticed an inverted handling of ``fseek``'s return value in function ``srslte_filesource_seek(...)``.
A sprious error message is printed, if the filesource is being seeked. Conversely, in case of a seek failure, no message is shown.
The behaviour is fixed in the attached pull request.
Kind Regards
Robert
References: http://man7.org/linux/man-pages/man3/fseek.3.html
> Fixed inverted handling of fseek result value in srslte_filesource_seek

- lib/examples/pdsch_enodeb.c
- lib/src/phy/phch/dci.c
Hi all,
the function ``dci_format_1As_pack(...)`` packs the new data indicator (ndi) incorrectly due to an inverted condition in line ``dci.c:675``: ``if (SRSLTE_RNTI_ISUSER(dci->rnti))``should be ``if (!SRSLTE_RNTI_ISUSER(dci->rnti))``.
For confidence, compare the inverse function ``dci_format_1As_unpack`` in line ``dci.c:785``.
Regards
Robert
> Fix ndi in dci_format1As_pack function

- lib/include/srslte/interfaces/enb_interfaces.h
- srsenb/hdr/stack/rrc/rrc.h
- srsenb/hdr/stack/upper/s1ap.h
- srsenb/src/stack/rrc/rrc.cc
- srsenb/src/stack/upper/s1ap.cc
This commit introduces CSFB (circuit switched fall-back) capabilities to
srsLTE.  Actually, all the eNB has to do is to send a
RrcConnectionRelease with the RedirectedCarrierInfo IE.
The MME triggers this by the S1AP CS Fallback Indicator IE, which may
be present either in the Initial Context Setup Requst or in the
UE Context Modification Request.
As srsLTE has no support for the UE Context Modification Request at all
yet (!), basic support for this message is introduced in this patch.
Both Mobile Originated and Mobile Terminated CSFB with a coupel of
different UE models have been verified using this patch in a setup
consisting of srsENB attached to an undisclosed EPC connected via SGsAP
to a complete  Osmocom 2G network.
Closes: #358
Closes: #363
> [ENB] Add CFSB support

- lib/include/srslte/asn1/asn1_utils.h
- lib/src/asn1/rrc_asn1_utils.cc
the last two fixes to remove all critical warnings from lgtm, of course, we need to backport those to the asn_libs.
> fixing two more issues reported by lgtm in asn1 libs

- lib/src/phy/ch_estimation/chest_dl.c
Fixed what I'm assuming was a typo in the `get_rsrp()` function. It now finds the maximum RSRP from the TX antenna ports, rather than the RX antenna. 
`get_rsrp()` (line 928 of chest_dl.c) now loops through the number of TX antenna ports and returns the maximum RSRP from get_rsrp_port(). 
`get_rsrp_port()` (line 900 of chest_dl.c) loops through the RX-antenna RSRP and returns the average. 
The RSRP values come from a 2D array `q->rsrp[RX_antenna][TX_port]`. 
Because the variable _i_ (in get_rsrp) ends up being used as q->rsrp[...][i], leads me to believe the fix to TX antenna port is correct.
Thanks,
Max
> get_rsrp fix for TX-port
